[package]
name = "soroban-option"
version = "0.0.0"
authors = ["Block TIme Financial, Inc <info@blocktimefinancial.com>"]
license = "MIT"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]
doctest = false

[features]
testutils = ["soroban-auth/testutils"]

[dependencies]
soroban-sdk = { path = "../soroban-sdk", features = ["testutils"] }
soroban-auth = { path = "../soroban-auth", features = ["testutils"] }

[dev_dependencies]
soroban-sdk = { path = "../soroban-sdk", features = ["testutils"] }
soroban-auth = { path = "../soroban-auth", features = ["testutils"] }